### PR TITLE
Added support for authentication

### PR DESCRIPTION
**Pull request by relvao**
- Added support for authentication 
- Fix EventEmitter inheritance
- Logging is now optional: client.debug = true;
- "ready_callback" now gets 2 params: err and clientInstance

### CODE REVIEW

**Comment by strk** [comment]
You shouldn't set release date in the NEWS file (will be set when it is released).
Addition of testcase is appreciated. I don't feel like merging this in w/out testing myself, and in order to test that I'll need some time to figure out how we're using node-varnish (if at all).

**Comment by relvao** [comment]
I'll keep your advice about the News file in mind. I suppose you don't need
me to re-publish it. Do you?
We were unable to use it internally without the auth support. I just hope
the changes are of any use. Feel free to publish it if/whenever you feel
appropriate.

Thanks,
Tiago

2014-02-03 strk notifications@github.com:

**Comment by strk** [comment]
On Mon, Feb 03, 2014 at 08:44:36AM -0800, Tiago Relvao wrote:

> I'll keep your advice about the News file in mind. I suppose you don't need
> me to re-publish it. Do you?

No no.
If you want another advice, don't mix functional and style changes
in a single commit/pull_request.

The ending newcolons... very useful, would have had no problem
merging them w/out testing much ;)

> We were unable to use it internally without the auth support. I just hope
> the changes are of any use. Feel free to publish it if/whenever you feel
> appropriate.

I'm sure it's useful, really only need to remember where I use it.
The last problem I had with varnish was support for version 3.0,
no idea if users of node-varnish were affected.

--strk;

> Thanks,
> Tiago
> 
> 2014-02-03 strk notifications@github.com:
> 
> > You shouldn't set release date in the NEWS file (will be set when it is
> > released).
> > Addition of testcase is appreciated. I don't feel like merging this in
> > w/out testing myself, and in order to test that I'll need some time to
> > figure out how we're using node-varnish (if at all).
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/Vizzuality/node-varnish/pull/7#issuecomment-33972476
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Vizzuality/node-varnish/pull/7#issuecomment-33973373

## 

 ()  ASCII ribbon campaign  --  Keep it simple !
 /\  http://strk.keybit.net/rants/ascii_mails.txt

**Comment by strk** [comment]
For the record, Windshaft-CartoDB seems to be using node-varnish...
If you want to help maybe you could see how to improve the Windshat-CartoDB test to use the privacy option. I bet the VarnishServerEmu is the same class (wonder if it should be moved into a separate project)

**Comment by strk** [comment]
That is: http://github.com/CartoDB/Windshaft-cartodb

**Comment by relvao** [comment]
Sure. I'll take a look later today.

2014-02-03 strk notifications@github.com:

**Comment by strk** [comment]
So, for the record. Windshaft-CartoDB is using it to invalidate caches on POST /style and DELETE /flush_cache.

See https://github.com/CartoDB/Windshaft-cartodb/issues/135

**Pull request merged**
